using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Queuey.Client.Waas;

/// <summary>
/// Renders a pulled workspace as <c>[QueueyQueue]</c> declarations — the bridge for a team adopting a
/// workspace that was configured in the console before anyone wrote it down.
/// </summary>
/// <remarks>
/// It emits <b>behaviour only</b>. Destinations stay in the deployment file, because that is where
/// they belong: they differ per environment and carry credential references. Generating a type with a
/// URL baked into it would undo the separation the whole design rests on.
/// </remarks>
public static class QueueCodeWriter
{
    /// <summary>Renders C# for every queue in <paramref name="file"/>, in a namespace of your choosing.</summary>
    public static string ForFile(DeploymentFile file, string @namespace = "Queues")
    {
        if (file is null) throw new ArgumentNullException(nameof(file));

        var sb = new StringBuilder();
        sb.AppendLine("using Queuey.Client.Waas;");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine("// Generated by `queuey pull --emit-code`. Behaviour only — where each queue");
        sb.AppendLine("// delivers stays in queuey.deploy.json, since it differs per environment.");

        foreach (KeyValuePair<string, DeploymentQueue> entry in file.Queues.OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            sb.AppendLine();
            sb.AppendLine(Attribute(entry.Key, entry.Value ?? new DeploymentQueue()));
            sb.AppendLine($"public sealed class {TypeName(entry.Key)} {{ }}");
        }

        return sb.ToString();
    }

    private static string Attribute(string name, DeploymentQueue q)
    {
        var args = new List<string> { $"\"{name}\"" };

        if (!string.IsNullOrWhiteSpace(q.Ordering)) args.Add($"Ordering = \"{q.Ordering}\"");
        if (q.DlqEnabled is { } d) args.Add($"DlqEnabled = {(d ? "true" : "false")}");
        if (q.RetentionDays is { } rd) args.Add($"RetentionDays = {rd}");
        if (q.Idempotent is { } i) args.Add($"Idempotent = {(i ? "true" : "false")}");

        return $"[QueueyQueue({string.Join(", ", args)})]";
    }

    /// <summary>Turns a queue name back into a PascalCase type name — the inverse of the convention.</summary>
    internal static string TypeName(string queueName)
    {
        var sb = new StringBuilder(queueName.Length);
        bool upper = true;

        foreach (char c in queueName)
        {
            if (!char.IsLetterOrDigit(c)) { upper = true; continue; }
            sb.Append(upper ? char.ToUpperInvariant(c) : c);
            upper = false;
        }

        // A name starting with a digit is a legal queue but not a legal identifier.
        if (sb.Length == 0 || char.IsDigit(sb[0])) sb.Insert(0, "Queue");
        return sb.ToString();
    }
}
